server.port: 8087

kmz-output-directory: "output-kmz"
geojson-output-directory: "output-geojson"

catalogue-url: "http://localhost:8086"
catalogue-username: "username"
catalogue-password: "password"

# default REST filesize override:
spring.servlet.multipart.max-file-size: "10MB"
spring.servlet.multipart.max-request-size: "10MB"
